### PR TITLE
fix: remove oldlogs

### PR DESCRIPTION
**Pull request by cafkafk**
Git is hard...

Refs: https://dbcjira.atlassian.net/browse/PLATFORM-2729

Resolves: #110

Signed-off-by: Christina Sørensen christina@cafkafk.com

### CODE REVIEW

**Review by johanot — CHANGES_REQUESTED** [review]
lgtm, except two nits:

- please run `cargo update -p dbc-rust-modules`
- please remove the now unused constant here: https://github.com/wharfix/wharfix/blob/f2873ee2a9770e094f222f53a81fc125c37f0500/src/main.rs#L419

**Comment by cafkafk** [comment]
> lgtm, except two nits:
> 
>     * please run `cargo update -p dbc-rust-modules`
> 
>     * please remove the now unused constant here: https://github.com/wharfix/wharfix/blob/f2873ee2a9770e094f222f53a81fc125c37f0500/src/main.rs#L419
> 
>     * _edit:_ also, remove the `allow(unused)` annotations on the "new-log" code pieces :)

makes sense, will do when back in office :+1:

**Comment by johanot** [comment]
> We do technically need them if we don't use all the log_levels actually...

Ah right. :)

**Review by johanot — APPROVED** [review]
Perfect, thanks! :mechanical_arm:

**Pull request merged**
