### PR TITLE
refactor: remove setting and getting statics unsafely with OnceLock

### PR DESCRIPTION
**Pull request by cafkafk**
- **refactor(gcroots): make `ADD_NIX_GCROOTS` safe**
- **refactor(indexfile): make indexfile safe**
- **refactor(servetype): make servetype safe**
- **refactor(targetdir): make targetdir safe**
- **refactor(blobcachedir): make blobcachedir safe**
- **refactor(substituters): make substituters safe**
- **refactor(sshprivatekey): make sshprivatekey safe**

### CODE REVIEW

**Comment by cafkafk** [comment]
and the `just i` integration test with hugepkgs does also pass :)

**Comment by johanot** [comment]
If refactoring anyway, why not just one single config struct with a single lock? :)

**Comment by cafkafk** [comment]
> If refactoring anyway, why not just one single config struct with a single lock? :)

My initial goal was just to purge a bit of unsafe, didn't wanna do anything too controversial like that. But it could make sense in relation to #98, although maybe that should first be done after #95 and #99?

**Comment by johanot** [comment]
> My initial goal was just to purge a bit of unsafe, didn't wanna do anything too controversial like that.

Sure! All of my comments are basically me not being overly proud of the Rust I wrote 4 years ago, so current-me is like: "Why not rewrite eeeeeeverything? :dagger: :laughing:  I'm totally fine with smaller steps though.

**Comment by cafkafk** [comment]
> > My initial goal was just to purge a bit of unsafe, didn't wanna do anything too controversial like that.
> 
> Sure! All of my comments are basically me not being overly proud of the Rust I wrote 4 years ago, so current-me is like: "Why not rewrite eeeeeeverything? 🗡️ 😆 I'm totally fine with smaller steps though.

To be fair, I think `OnceLock` was only recently introduced in like 1.70~, so back then doing something like this safely was a way bigger pain >_>

**Comment by johanot** [comment]
Yeah I saw it went into std :) it wasn't that bad, previously we just used a crate, e.g. https://crates.io/crates/once_cell.

**Comment by srhb** [comment]
As a rust newbie that doesn't understand the implications of unsafe, but just get a vague chill in my spine when I see it, this looks like a nice incremental improvement. :sweat_smile:

**Review by srhb — APPROVED** [review]

**Pull request merged**
