### PR TITLE
ci: fix bump-o-matic, which was never updated to use flakes and crane

### PR DESCRIPTION
**Pull request by johanot**

### CODE REVIEW

**Comment by johanot** [comment]
Hmm... Updating the PR action version didn't do the trick :( .. @srhb Do you remember why: `fatal: could not read Username for 'https://github.com/': No such device or address` as seen in my test bump here: https://github.com/wharfix/wharfix/actions/runs/5304862799/jobs/9601460214 .. Wonder if it's something on your hetzner-github-builder ?

**Comment by srhb** [comment]
I think it is. Sorry I'm a little busy now, I'll try to get back to it this week! :)

**Comment by srhb** [comment]
@johanot I think I'm closer. #70 merges into this branch. Still getting a slightly weird error, "Pull request Pull request is in clean status" that I have yet to analyze.

**Comment by srhb** [comment]
imo if you merge that, I'll merge this, and will continue to debug once it actually happens in master.

**Review by srhb — APPROVED** [review]

**Pull request merged**
