### PR TITLE
Faster oom test

### PR DESCRIPTION
**Pull request by johanot**
Build on top of #97, so drafting.

Also haven't tested that this test actually fails before streaming was merged. (yet)

### CODE REVIEW

**Comment by johanot** [comment]
Added beef55f , which can be dropped before merging as per reviewers preference. It verifies that the test case actually fails when run against the old non-streaming version of Wharfix - primarily as a help for this review.

**Review by cafkafk — COMMENTED** [review]
> Added [beef55f](https://github.com/wharfix/wharfix/commit/beef55fe899ae55a61d1bae3246070f8b26196f2) , which can be dropped before merging as per reviewers preference. It verifies that the test case actually fails when run against the old non-streaming version of Wharfix - primarily as a help for this review.

I think we should keep it, it's nice to have to verify changes to the oom-test in the future ¯\\_(ツ)_/¯

**Comment by johanot** [comment]
Ok.. 

1a9dd4c converts to callPackage.

fb489f8 takes it a step further and converts the "positive" and "negative" oom scenario into two different test cases. It has the advantages that we don't need to re-run the negative test each time wharfix changes, especially since the negative test is slooow due to having to wait for docker pull 5 times retry before it finally gives up. It also underlines why having the negative scenario in there is perhaps a bad idea in the first place? One could argue that we should add negative scenarios for _all_ tests then (i.e. for "ref" as well)? Also, it makes it obvious that the wharfix flake now depends on an older version of self (which is maybe not nice?) - which - it did before fb489f8 as well; only difference is that now it has become more visible.

I'm fine with merging this with or without the negative scenario :) it's up to the reviewer.

**Review by cafkafk — APPROVED** [review]
> It also underlines why having the negative scenario in there is perhaps a bad idea in the first place?

I don't have a problem with keeping it either, but I do see how it might seem unnecessary .

> One could argue that we should add negative scenarios for all tests then (i.e. for "ref" as well)?

Consider e.g. if the kubernetes image for some reason changes size at some point with a nixpkgs bump, to the point that you wouldn't need streaming to avoid oom, in that case, the test would silently stop working. I don't think it's the same for e.g. ref in that regard. 

Still, that might be overly cautious :p 

> Also, it makes it obvious that the wharfix flake now depends on an older version of self (which is maybe not nice?)

Alternatively, it could be gotten with a `fetchFromGitHub` or something? Not sure if it's nicer that way... 

---

I think I lean keeping it like this, but I'm very fine with not testing against the older version instead if you prefer. Either way cool PR, ty :)

**Comment by johanot** [comment]
> Consider e.g. if the kubernetes image for some reason changes size at some point with a nixpkgs bump

I thought of that too, but I didn't wanna pin and instantiate an entire nixpkgs (and potentially re-build kubernetes) just to get a reproducible layer :p Instead, we could do something like this: 20c7596 . Basically just download and pin some big enough artifact  (which is not an _output_). Let me hear what you think.

**Comment by cafkafk** [comment]
> > Consider e.g. if the kubernetes image for some reason changes size at some point with a nixpkgs bump
> 
> I thought of that too, but I didn't wanna pin and instantiate an entire nixpkgs (and potentially re-build kubernetes) just to get a reproducible layer :p Instead, we could do something like this: [20c7596](https://github.com/wharfix/wharfix/commit/20c75961d09262ec12650b17f26039b6a496fe9f) . Basically just download and pin some big enough artifact (which is not an _output_). Let me hear what you think.

Let's do this then, seems reasonable enough :+1:

**Comment by johanot** [comment]
Mind re-approving then? :) Then let's just merge this.

**Review by cafkafk — APPROVED** [review]

**Pull request merged**
